### ISSUE TITLE
Snapshot version cannot be used, as snapshot version is not generated correctly for Gradle

### ISSUE THREAD

**Issue by Virtlink** [metaborg/gitonium#1]
The snapshot version generated by Gitonium is incorrect. According to [Gradle version ordering](https://docs.gradle.org/current/userguide/single_versions.html#version_ordering), the snapshot version should start with a version higher than the latest release to be sorted correctly. For example, `0.14.0-develop-SNAPSHOT` (or `0.14.0-9db6fa-SNAPSHOT` on detached HEAD) instead of `develop-SNAPSHOT`. Without the version, Gradle will always order the snapshot dependency lower than the releases, therefore making it impossible to refer to a snapshot dependency when any of the transitive dependencies refer a release, as the release takes precedence.

```
(lower precedence              -->              higher precedence)

develop-SNAPSHOT  <  0.13.0  <  0.14.0  <  0.14.0-develop-SNAPSHOT
```

Existing Gradle plugins such as [fr.brouillard.oss.gradle.jgitver](https://github.com/jgitver/gradle-jgitver-plugin) and [com.palantir.git-version](https://github.com/palantir/gradle-git-version) solve this by traversing the commits and deriving the version from the highest (or latest) declared version tag in the commit chain from HEAD to the farthest reachable base.

**Comment by Gohla** [comment]
Fixed by https://github.com/metaborg/gitonium/pull/3.
